#!/bin/bash
input_file="$(java -jar target/tiny_basic_compiler-1.0.jar $@)"

if [[ ! -f $input_file ]]
then
  echo "$input_file"

else
  file_out=$(echo "$input_file" | cut -f 1 -d '.')
  nasm -i ./include/ -f elf64 -o $file_out.o $input_file
  ld -o $file_out $file_out.o
fi
