<program> ::= <line>+
<line> ::= <number> "0 " <statement> "\n"

<statement> ::= "PRINT " (<string> | <expression>) ("," (<string> | <expression>))* |
              "IF " <expression> <relational_op> <expression> " THEN " <statement> |
              "INPUT " <identifier_list> |
              "LET " <identifier> "=" <expression> |
              "GOTO " <expression> |
              "GOSUB " <expression> |
              "RETURN " |
              "END "

<digit> ::= [0-9]
<uppercase> ::= [A-Z]
<lowercase> ::= [a-z]
<factor> ::= ("+" | "-") factor | <identifier> | <number> | "(" <expression> ")"
<term> ::= <factor> (("*" | "/") <factor>)*
<expression> ::= <term> (("+" | "-") <term>)*
<identifier> ::= <uppercase>
<identifier_list> ::= <identifier> ("," <identifier>)*
<number> ::= <digit> <digit>*
<relational_op> ::= "<" (">" | "=") | ">" ("<" | "=") | "="
<string> ::= "'" (<uppercase> | <lowercase> | <digit>)+ "'"
